// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbdixeFeNCSq3u6HDYULPokmYNjITvrQo',
    appId: '1:80182142639:web:7cb164ff4260f4aaac565a',
    messagingSenderId: '80182142639',
    projectId: 'up-bhulekh-ios',
    authDomain: 'up-bhulekh-ios.firebaseapp.com',
    storageBucket: 'up-bhulekh-ios.appspot.com',
    measurementId: 'G-3HHHFCQP82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuJxPDMajuEbbHXb-1wCETOntvAe6YfPA',
    appId: '1:80182142639:android:4180e0a7fd6ccee6ac565a',
    messagingSenderId: '80182142639',
    projectId: 'up-bhulekh-ios',
    storageBucket: 'up-bhulekh-ios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6XcBIJt9mdozELp_B9r0jPNyI7xw31bk',
    appId: '1:80182142639:ios:3067b283d6a13e44ac565a',
    messagingSenderId: '80182142639',
    projectId: 'up-bhulekh-ios',
    storageBucket: 'up-bhulekh-ios.appspot.com',
    iosBundleId: 'com.clovenandworks.bhulekhUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6XcBIJt9mdozELp_B9r0jPNyI7xw31bk',
    appId: '1:80182142639:ios:39cc30ae482ea916ac565a',
    messagingSenderId: '80182142639',
    projectId: 'up-bhulekh-ios',
    storageBucket: 'up-bhulekh-ios.appspot.com',
    iosBundleId: 'com.example.bhulekhUp.RunnerTests',
  );
}
